# Generated by Django 4.0.4 on 2022-04-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_title_collection_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='name',
            new_name='title',
        ),
    ]
